import {useState, useEffect,} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'

// npm run dev


export default function Home() {
  const [data, setData] = useState([]);
  const [userID, setUserID] = useState("1")
  // chat dataを取得
  useEffect(() => {
    axios.get('http://localhost:8080/room')
      .then((res) => {
        console.log(res.data);
        setData(res.data);
      })
      .catch((err) => {
        console.log(err);
      })
  }, []);



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to CHAT APP

        </h1>
      
        
        

        
    
        {
          data.map((item,index) => {
            const roomURL = '/room/' + item.RoomName;
            return (
              <div className={styles.grid} key={index}>
                <a href={roomURL} className={styles.card} >
                  <h2>{item.RoomName} &rarr;</h2>
                </a>
              </div>
            )
          })
        }




        

       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}